[platformio]
default_envs = pico_w

[env:native]
platform = native
build_flags = -std=gnu++17
test_build_src = no

[env:pico_w]
platform = raspberrypi
board = rpipicow
framework = arduino
monitor_speed = 115200
build_flags =
  -D CORE_DEBUG_LEVEL=5
  -D PICO_W
  ; -D DURATION_DISPLAY
  ; -D ELECTRIC_HEATING
  ; -D HYDRAULIC_AVAILABLE=false  ; uncomment to run in degraded mode (electric only)
  -std=gnu++17
lib_deps =
  adafruit/Adafruit BusIO@^1.14.1
  adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
  adafruit/RTClib@^2.1.1
  arduino-libraries/SD@^1.2.4
  thijse/ArduinoLog@^1.1.1
  smougenot/TM1637
  4-20ma/ModbusMaster@^2.0.1

