/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_OTLP_COMMON_PB_H_INCLUDED
#define PB_OTLP_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _otlp_AnyValue {
    pb_size_t which_value;
    union {
        char string_value[40];
    } value;
} otlp_AnyValue;

typedef struct _otlp_KeyValue {
    char key[16];
    bool has_value;
    otlp_AnyValue value;
} otlp_KeyValue;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define otlp_AnyValue_init_default               {0, {""}}
#define otlp_KeyValue_init_default               {"", false, otlp_AnyValue_init_default}
#define otlp_AnyValue_init_zero                  {0, {""}}
#define otlp_KeyValue_init_zero                  {"", false, otlp_AnyValue_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define otlp_AnyValue_string_value_tag           1
#define otlp_KeyValue_key_tag                    1
#define otlp_KeyValue_value_tag                  2

/* Struct field encoding specification for nanopb */
#define otlp_AnyValue_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    STRING,   (value,string_value,value.string_value),   1)
#define otlp_AnyValue_CALLBACK NULL
#define otlp_AnyValue_DEFAULT NULL

#define otlp_KeyValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define otlp_KeyValue_CALLBACK NULL
#define otlp_KeyValue_DEFAULT NULL
#define otlp_KeyValue_value_MSGTYPE otlp_AnyValue

extern const pb_msgdesc_t otlp_AnyValue_msg;
extern const pb_msgdesc_t otlp_KeyValue_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define otlp_AnyValue_fields &otlp_AnyValue_msg
#define otlp_KeyValue_fields &otlp_KeyValue_msg

/* Maximum encoded size of messages (where known) */
#define OTLP_COMMON_PB_H_MAX_SIZE                otlp_KeyValue_size
#define otlp_AnyValue_size                       41
#define otlp_KeyValue_size                       60

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
