/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_OTLP_METRICS_SERVICE_PB_H_INCLUDED
#define PB_OTLP_METRICS_SERVICE_PB_H_INCLUDED
#include <pb.h>
#include "metrics.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _otlp_ExportMetricsServiceRequest {
    pb_size_t resource_metrics_count;
    otlp_ResourceMetrics resource_metrics[1];
} otlp_ExportMetricsServiceRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define otlp_ExportMetricsServiceRequest_init_default {0, {otlp_ResourceMetrics_init_default}}
#define otlp_ExportMetricsServiceRequest_init_zero {0, {otlp_ResourceMetrics_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define otlp_ExportMetricsServiceRequest_resource_metrics_tag 1

/* Struct field encoding specification for nanopb */
#define otlp_ExportMetricsServiceRequest_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  resource_metrics,   1)
#define otlp_ExportMetricsServiceRequest_CALLBACK NULL
#define otlp_ExportMetricsServiceRequest_DEFAULT NULL
#define otlp_ExportMetricsServiceRequest_resource_metrics_MSGTYPE otlp_ResourceMetrics

extern const pb_msgdesc_t otlp_ExportMetricsServiceRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define otlp_ExportMetricsServiceRequest_fields &otlp_ExportMetricsServiceRequest_msg

/* Maximum encoded size of messages (where known) */
#define OTLP_METRICS_SERVICE_PB_H_MAX_SIZE       otlp_ExportMetricsServiceRequest_size
#define otlp_ExportMetricsServiceRequest_size    24779

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
