/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_OTLP_RESOURCE_PB_H_INCLUDED
#define PB_OTLP_RESOURCE_PB_H_INCLUDED
#include <pb.h>
#include "common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _otlp_Resource {
    pb_size_t attributes_count;
    otlp_KeyValue attributes[1];
} otlp_Resource;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define otlp_Resource_init_default               {0, {otlp_KeyValue_init_default}}
#define otlp_Resource_init_zero                  {0, {otlp_KeyValue_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define otlp_Resource_attributes_tag             1

/* Struct field encoding specification for nanopb */
#define otlp_Resource_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  attributes,        1)
#define otlp_Resource_CALLBACK NULL
#define otlp_Resource_DEFAULT NULL
#define otlp_Resource_attributes_MSGTYPE otlp_KeyValue

extern const pb_msgdesc_t otlp_Resource_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define otlp_Resource_fields &otlp_Resource_msg

/* Maximum encoded size of messages (where known) */
#define OTLP_RESOURCE_PB_H_MAX_SIZE              otlp_Resource_size
#define otlp_Resource_size                       63

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
