#include "config.h"
#if DRYER_WIFI

/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "metrics.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(otlp_NumberDataPoint, otlp_NumberDataPoint, AUTO)


PB_BIND(otlp_Gauge, otlp_Gauge, AUTO)


PB_BIND(otlp_Metric, otlp_Metric, AUTO)


PB_BIND(otlp_ScopeMetrics, otlp_ScopeMetrics, 4)


PB_BIND(otlp_ResourceMetrics, otlp_ResourceMetrics, 4)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif


#endif // DRYER_WIFI
