#include "config.h"
#if DRYER_WIFI

/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "metrics_service.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(otlp_ExportMetricsServiceRequest, otlp_ExportMetricsServiceRequest, 4)




#endif // DRYER_WIFI
