#include "config.h"
#if DRYER_WIFI

/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "resource.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(otlp_Resource, otlp_Resource, AUTO)




#endif // DRYER_WIFI
